// Package main demonstrates how the LLM *automatically* triggers the
// built-in "delegate_to_subagent" tool when facing a complex task.
//
// How it works:
//   - Every Agent (non-PTC) gets "delegate_to_subagent" injected into its
//     tool list automatically by collectAllAvailableTools().
//   - When the main Agent encounters a task that benefits from isolated
//     sub-execution, the LLM calls the tool on its own.
//   - The SubAgent runs with the parent Service's tools (filtered by
//     tools_allowlist / tools_denylist if the LLM provides them).
//
// This example provides two domain-specific tools (search_topic, write_report),
// then asks the Agent to research two separate topics and produce a combined
// report. A well-aligned LLM will naturally delegate each research step to a
// SubAgent and then merge the results itself.
//
// Debug mode is enabled via WithDebug(true) — you will see:
//   - Full prompts sent to the LLM each round
//   - Every tool call and result
//   - SubAgent progress for each delegated task
//
// Usage:
//
//	go run examples/subagent/auto_delegation/main.go
package main

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/liliang-cn/rago/v2/pkg/agent"
)

// ── Fake knowledge store ─────────────────────────────────────────────────────

var articles = map[string][]struct{ Title, Body string }{
	"microservices": {
		{
			Title: "What are Microservices?",
			Body: "Microservices decompose an application into small, independently deployable " +
				"services. Each service owns its data and exposes an API. Key benefits: " +
				"independent scaling, polyglot persistence, and fault isolation.",
		},
		{
			Title: "Microservices vs Monolith",
			Body: "Monoliths are simpler to start with but become hard to scale. " +
				"Microservices add operational complexity (service mesh, distributed tracing) " +
				"but enable teams to deploy independently at scale.",
		},
	},
	"kubernetes": {
		{
			Title: "Kubernetes Overview",
			Body: "Kubernetes (k8s) automates container scheduling, scaling, and self-healing. " +
				"Core primitives: Pod, Deployment, Service, Ingress, ConfigMap. " +
				"It is the de-facto standard for running microservices in production.",
		},
		{
			Title: "Kubernetes Networking",
			Body: "Every Pod gets its own IP. Services provide stable DNS and load-balancing. " +
				"Ingress controllers expose HTTP routes. Network policies enforce isolation.",
		},
	},
	"golang": {
		{
			Title: "Go Language Design",
			Body: "Go emphasises simplicity, fast compilation, and built-in concurrency via " +
				"goroutines and channels. Its garbage collector is tuned for low-latency services.",
		},
	},
}

// searchTopic returns articles whose topic matches the query.
func searchTopic(_ context.Context, args map[string]interface{}) (interface{}, error) {
	topic, _ := args["topic"].(string)
	if topic == "" {
		return nil, fmt.Errorf("topic is required")
	}
	topic = strings.ToLower(topic)

	var hits []map[string]string
	for key, arts := range articles {
		if strings.Contains(key, topic) || strings.Contains(topic, key) {
			for _, a := range arts {
				hits = append(hits, map[string]string{"title": a.Title, "body": a.Body})
			}
		}
	}
	if len(hits) == 0 {
		return map[string]interface{}{"topic": topic, "articles": nil, "count": 0}, nil
	}
	return map[string]interface{}{"topic": topic, "articles": hits, "count": len(hits)}, nil
}

// writeReport formats the given sections into a Markdown report.
func writeReport(_ context.Context, args map[string]interface{}) (interface{}, error) {
	title, _ := args["title"].(string)
	sections, _ := args["sections"].(string)
	if title == "" || sections == "" {
		return nil, fmt.Errorf("title and sections are required")
	}
	report := fmt.Sprintf("# %s\n\n%s\n\n---\n*Generated by RAGO*", title, sections)
	return map[string]interface{}{"report": report, "char_count": len(report)}, nil
}

// ── Main ─────────────────────────────────────────────────────────────────────

func main() {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	fmt.Println("=== SubAgent Auto-Delegation Example ===")
	fmt.Println("The main Agent will delegate research sub-tasks to SubAgents")
	fmt.Println("and merge results to produce a final report.")
	fmt.Println()

	// ── Build the Service ────────────────────────────────────────────────────
	searchTool := agent.BuildTool("search_topic").
		Description("Search the knowledge base for articles on a given topic. Returns a list of articles.").
		Param("topic", agent.TypeString, "Topic to search (e.g. 'microservices', 'kubernetes', 'golang')", agent.Required()).
		Handler(searchTopic).
		Build()

	reportTool := agent.BuildTool("write_report").
		Description("Format research sections into a Markdown report.").
		Param("title", agent.TypeString, "Report title", agent.Required()).
		Param("sections", agent.TypeString, "Markdown body of the report (may include ## headings)", agent.Required()).
		Handler(writeReport).
		Build()

	svc, err := agent.New("Orchestrator").
		WithPrompt(
			"You are an expert technical writer. "+
				"For research-heavy tasks, break them into focused sub-tasks and "+
				"delegate each to a sub-agent using the delegate_to_subagent tool. "+
				"Each sub-agent should use search_topic to gather information on ONE topic. "+
				"When delegating, always set max_turns=10. "+
				"After all research is done, use write_report to produce the final document.").
		WithTool(searchTool).
		WithTool(reportTool).
		WithProgress(func(e agent.ProgressEvent) {
			switch e.Type {
			case "tool_call":
				fmt.Printf("  ▶ Tool: %s — %s\n", e.Tool, e.Message)
			case "tool_result":
				fmt.Printf("  ✓ %s\n", e.Message)
			case "thinking":
				fmt.Printf("  💭 %s\n", e.Message)
			}
		}).
		WithDebug(true). // ← prints full LLM prompts and responses
		Build()
	if err != nil {
		log.Fatalf("build: %v", err)
	}
	defer svc.Close()

	// ── Run ─────────────────────────────────────────────────────────────────
	goal := "Research both 'microservices' and 'kubernetes', then write a combined technical report titled 'Building Cloud-Native Systems' with a section for each topic."

	fmt.Printf("Goal: %s\n\n", goal)
	fmt.Println(strings.Repeat("─", 60))

	result, err := svc.Run(ctx, goal, agent.WithMaxTurns(15))
	if err != nil {
		log.Fatalf("run: %v", err)
	}

	fmt.Println(strings.Repeat("─", 60))
	fmt.Println("\n=== Final Result ===")
	fmt.Println(result.Text())
}
