// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/ptc/grpc/proto/ptc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type of chunk
type ExecuteChunk_ChunkType int32

const (
	ExecuteChunk_OUTPUT    ExecuteChunk_ChunkType = 0
	ExecuteChunk_LOG       ExecuteChunk_ChunkType = 1
	ExecuteChunk_TOOL_CALL ExecuteChunk_ChunkType = 2
	ExecuteChunk_ERROR     ExecuteChunk_ChunkType = 3
	ExecuteChunk_DONE      ExecuteChunk_ChunkType = 4
)

// Enum value maps for ExecuteChunk_ChunkType.
var (
	ExecuteChunk_ChunkType_name = map[int32]string{
		0: "OUTPUT",
		1: "LOG",
		2: "TOOL_CALL",
		3: "ERROR",
		4: "DONE",
	}
	ExecuteChunk_ChunkType_value = map[string]int32{
		"OUTPUT":    0,
		"LOG":       1,
		"TOOL_CALL": 2,
		"ERROR":     3,
		"DONE":      4,
	}
)

func (x ExecuteChunk_ChunkType) Enum() *ExecuteChunk_ChunkType {
	p := new(ExecuteChunk_ChunkType)
	*p = x
	return p
}

func (x ExecuteChunk_ChunkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecuteChunk_ChunkType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_ptc_grpc_proto_ptc_proto_enumTypes[0].Descriptor()
}

func (ExecuteChunk_ChunkType) Type() protoreflect.EnumType {
	return &file_pkg_ptc_grpc_proto_ptc_proto_enumTypes[0]
}

func (x ExecuteChunk_ChunkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecuteChunk_ChunkType.Descriptor instead.
func (ExecuteChunk_ChunkType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_ptc_grpc_proto_ptc_proto_rawDescGZIP(), []int{2, 0}
}

// ExecuteRequest represents a code execution request
type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Code to execute
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Language of the code (javascript, wasm)
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	// Context variables to inject (JSON encoded)
	Context map[string]string `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// List of allowed tools
	Tools []string `protobuf:"bytes,4,rep,name=tools,proto3" json:"tools,omitempty"`
	// Timeout in milliseconds
	TimeoutMs int32 `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	// Maximum memory in MB
	MaxMemoryMb   int32 `protobuf:"varint,6,opt,name=max_memory_mb,json=maxMemoryMb,proto3" json:"max_memory_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_pkg_ptc_grpc_proto_ptc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ptc_grpc_proto_ptc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ptc_grpc_proto_ptc_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ExecuteRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ExecuteRequest) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ExecuteRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ExecuteRequest) GetMaxMemoryMb() int32 {
	if x != nil {
		return x.MaxMemoryMb
	}
	return 0
}

// ExecuteResponse represents the result of code execution
type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether execution succeeded
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Output from execution (JSON encoded)
	Output string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	// Return value from code (JSON encoded)
	ReturnValue string `protobuf:"bytes,3,opt,name=return_value,json=returnValue,proto3" json:"return_value,omitempty"`
	// Error message if failed
	Error string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// Tool calls made during execution
	ToolCalls []*ToolCallRecord `protobuf:"bytes,5,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	// Logs from console.log
	Logs []string `protobuf:"bytes,6,rep,name=logs,proto3" json:"logs,omitempty"`
	// Duration in milliseconds
	DurationMs int64 `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Execution ID
	ExecutionId   string `protobuf:"bytes,8,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_pkg_ptc_grpc_proto_ptc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ptc_grpc_proto_ptc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_ptc_grpc_proto_ptc_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecuteResponse) GetReturnValue() string {
	if x != nil {
		return x.ReturnValue
	}
	return ""
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetToolCalls() []*ToolCallRecord {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *ExecuteResponse) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ExecuteResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ExecuteResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

// ExecuteChunk represents a chunk of streaming output
type ExecuteChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chunk type
	Type ExecuteChunk_ChunkType `protobuf:"varint,1,opt,name=type,proto3,enum=ptc.ExecuteChunk_ChunkType" json:"type,omitempty"`
	// Chunk content
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Timestamp
	TimestampMs   int64 `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteChunk) Reset() {
	*x = ExecuteChunk{}
	mi := &file_pkg_ptc_grpc_proto_ptc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteChunk) ProtoMessage() {}

func (x *ExecuteChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ptc_grpc_proto_ptc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteChunk.ProtoReflect.Descriptor instead.
func (*ExecuteChunk) Descriptor() ([]byte, []int) {
	return file_pkg_ptc_grpc_proto_ptc_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteChunk) GetType() ExecuteChunk_ChunkType {
	if x != nil {
		return x.Type
	}
	return ExecuteChunk_OUTPUT
}

func (x *ExecuteChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ExecuteChunk) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// ToolCallRecord represents a tool call made during execution
type ToolCallRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tool name
	ToolName string `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Arguments passed (JSON encoded)
	Arguments string `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	// Result returned (JSON encoded)
	Result string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	// Error if failed
	Error string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// Duration in milliseconds
	DurationMs    int64 `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallRecord) Reset() {
	*x = ToolCallRecord{}
	mi := &file_pkg_ptc_grpc_proto_ptc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallRecord) ProtoMessage() {}

func (x *ToolCallRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ptc_grpc_proto_ptc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallRecord.ProtoReflect.Descriptor instead.
func (*ToolCallRecord) Descriptor() ([]byte, []int) {
	return file_pkg_ptc_grpc_proto_ptc_proto_rawDescGZIP(), []int{3}
}

func (x *ToolCallRecord) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCallRecord) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

func (x *ToolCallRecord) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ToolCallRecord) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ToolCallRecord) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// ListToolsRequest requests available tools
type ListToolsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by category
	Category      string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_pkg_ptc_grpc_proto_ptc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ptc_grpc_proto_ptc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ptc_grpc_proto_ptc_proto_rawDescGZIP(), []int{4}
}

func (x *ListToolsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// ListToolsResponse contains available tools
type ListToolsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of tools
	Tools         []*ToolInfo `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_pkg_ptc_grpc_proto_ptc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ptc_grpc_proto_ptc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_ptc_grpc_proto_ptc_proto_rawDescGZIP(), []int{5}
}

func (x *ListToolsResponse) GetTools() []*ToolInfo {
	if x != nil {
		return x.Tools
	}
	return nil
}

// GetToolInfoRequest requests info about a specific tool
type GetToolInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tool name
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToolInfoRequest) Reset() {
	*x = GetToolInfoRequest{}
	mi := &file_pkg_ptc_grpc_proto_ptc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToolInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToolInfoRequest) ProtoMessage() {}

func (x *GetToolInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ptc_grpc_proto_ptc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToolInfoRequest.ProtoReflect.Descriptor instead.
func (*GetToolInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ptc_grpc_proto_ptc_proto_rawDescGZIP(), []int{6}
}

func (x *GetToolInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetToolInfoResponse contains tool information
type GetToolInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tool information
	Tool *ToolInfo `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	// Whether tool exists
	Exists        bool `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToolInfoResponse) Reset() {
	*x = GetToolInfoResponse{}
	mi := &file_pkg_ptc_grpc_proto_ptc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToolInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToolInfoResponse) ProtoMessage() {}

func (x *GetToolInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ptc_grpc_proto_ptc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToolInfoResponse.ProtoReflect.Descriptor instead.
func (*GetToolInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_ptc_grpc_proto_ptc_proto_rawDescGZIP(), []int{7}
}

func (x *GetToolInfoResponse) GetTool() *ToolInfo {
	if x != nil {
		return x.Tool
	}
	return nil
}

func (x *GetToolInfoResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// ToolInfo contains information about a tool
type ToolInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tool name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Tool description
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Parameter schema (JSON Schema encoded)
	Parameters string `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	// Tool category (rag, mcp, skill, custom)
	Category      string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolInfo) Reset() {
	*x = ToolInfo{}
	mi := &file_pkg_ptc_grpc_proto_ptc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolInfo) ProtoMessage() {}

func (x *ToolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ptc_grpc_proto_ptc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolInfo.ProtoReflect.Descriptor instead.
func (*ToolInfo) Descriptor() ([]byte, []int) {
	return file_pkg_ptc_grpc_proto_ptc_proto_rawDescGZIP(), []int{8}
}

func (x *ToolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolInfo) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

func (x *ToolInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

var File_pkg_ptc_grpc_proto_ptc_proto protoreflect.FileDescriptor

const file_pkg_ptc_grpc_proto_ptc_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/ptc/grpc/proto/ptc.proto\x12\x03ptc\"\x91\x02\n" +
	"\x0eExecuteRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12:\n" +
	"\acontext\x18\x03 \x03(\v2 .ptc.ExecuteRequest.ContextEntryR\acontext\x12\x14\n" +
	"\x05tools\x18\x04 \x03(\tR\x05tools\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x05R\ttimeoutMs\x12\"\n" +
	"\rmax_memory_mb\x18\x06 \x01(\x05R\vmaxMemoryMb\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x02\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12!\n" +
	"\freturn_value\x18\x03 \x01(\tR\vreturnValue\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x122\n" +
	"\n" +
	"tool_calls\x18\x05 \x03(\v2\x13.ptc.ToolCallRecordR\ttoolCalls\x12\x12\n" +
	"\x04logs\x18\x06 \x03(\tR\x04logs\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x12!\n" +
	"\fexecution_id\x18\b \x01(\tR\vexecutionId\"\xc2\x01\n" +
	"\fExecuteChunk\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.ptc.ExecuteChunk.ChunkTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\"D\n" +
	"\tChunkType\x12\n" +
	"\n" +
	"\x06OUTPUT\x10\x00\x12\a\n" +
	"\x03LOG\x10\x01\x12\r\n" +
	"\tTOOL_CALL\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\b\n" +
	"\x04DONE\x10\x04\"\x9a\x01\n" +
	"\x0eToolCallRecord\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\tR\targuments\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\".\n" +
	"\x10ListToolsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\"8\n" +
	"\x11ListToolsResponse\x12#\n" +
	"\x05tools\x18\x01 \x03(\v2\r.ptc.ToolInfoR\x05tools\"(\n" +
	"\x12GetToolInfoRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"P\n" +
	"\x13GetToolInfoResponse\x12!\n" +
	"\x04tool\x18\x01 \x01(\v2\r.ptc.ToolInfoR\x04tool\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"|\n" +
	"\bToolInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x01(\tR\n" +
	"parameters\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory2\xfb\x01\n" +
	"\n" +
	"PTCService\x124\n" +
	"\aExecute\x12\x13.ptc.ExecuteRequest\x1a\x14.ptc.ExecuteResponse\x129\n" +
	"\rExecuteStream\x12\x13.ptc.ExecuteRequest\x1a\x11.ptc.ExecuteChunk0\x01\x12:\n" +
	"\tListTools\x12\x15.ptc.ListToolsRequest\x1a\x16.ptc.ListToolsResponse\x12@\n" +
	"\vGetToolInfo\x12\x17.ptc.GetToolInfoRequest\x1a\x18.ptc.GetToolInfoResponseB/Z-github.com/liliang-cn/agent-go/pkg/ptc/grpc/pbb\x06proto3"

var (
	file_pkg_ptc_grpc_proto_ptc_proto_rawDescOnce sync.Once
	file_pkg_ptc_grpc_proto_ptc_proto_rawDescData []byte
)

func file_pkg_ptc_grpc_proto_ptc_proto_rawDescGZIP() []byte {
	file_pkg_ptc_grpc_proto_ptc_proto_rawDescOnce.Do(func() {
		file_pkg_ptc_grpc_proto_ptc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_ptc_grpc_proto_ptc_proto_rawDesc), len(file_pkg_ptc_grpc_proto_ptc_proto_rawDesc)))
	})
	return file_pkg_ptc_grpc_proto_ptc_proto_rawDescData
}

var file_pkg_ptc_grpc_proto_ptc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_ptc_grpc_proto_ptc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_ptc_grpc_proto_ptc_proto_goTypes = []any{
	(ExecuteChunk_ChunkType)(0), // 0: ptc.ExecuteChunk.ChunkType
	(*ExecuteRequest)(nil),      // 1: ptc.ExecuteRequest
	(*ExecuteResponse)(nil),     // 2: ptc.ExecuteResponse
	(*ExecuteChunk)(nil),        // 3: ptc.ExecuteChunk
	(*ToolCallRecord)(nil),      // 4: ptc.ToolCallRecord
	(*ListToolsRequest)(nil),    // 5: ptc.ListToolsRequest
	(*ListToolsResponse)(nil),   // 6: ptc.ListToolsResponse
	(*GetToolInfoRequest)(nil),  // 7: ptc.GetToolInfoRequest
	(*GetToolInfoResponse)(nil), // 8: ptc.GetToolInfoResponse
	(*ToolInfo)(nil),            // 9: ptc.ToolInfo
	nil,                         // 10: ptc.ExecuteRequest.ContextEntry
}
var file_pkg_ptc_grpc_proto_ptc_proto_depIdxs = []int32{
	10, // 0: ptc.ExecuteRequest.context:type_name -> ptc.ExecuteRequest.ContextEntry
	4,  // 1: ptc.ExecuteResponse.tool_calls:type_name -> ptc.ToolCallRecord
	0,  // 2: ptc.ExecuteChunk.type:type_name -> ptc.ExecuteChunk.ChunkType
	9,  // 3: ptc.ListToolsResponse.tools:type_name -> ptc.ToolInfo
	9,  // 4: ptc.GetToolInfoResponse.tool:type_name -> ptc.ToolInfo
	1,  // 5: ptc.PTCService.Execute:input_type -> ptc.ExecuteRequest
	1,  // 6: ptc.PTCService.ExecuteStream:input_type -> ptc.ExecuteRequest
	5,  // 7: ptc.PTCService.ListTools:input_type -> ptc.ListToolsRequest
	7,  // 8: ptc.PTCService.GetToolInfo:input_type -> ptc.GetToolInfoRequest
	2,  // 9: ptc.PTCService.Execute:output_type -> ptc.ExecuteResponse
	3,  // 10: ptc.PTCService.ExecuteStream:output_type -> ptc.ExecuteChunk
	6,  // 11: ptc.PTCService.ListTools:output_type -> ptc.ListToolsResponse
	8,  // 12: ptc.PTCService.GetToolInfo:output_type -> ptc.GetToolInfoResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_ptc_grpc_proto_ptc_proto_init() }
func file_pkg_ptc_grpc_proto_ptc_proto_init() {
	if File_pkg_ptc_grpc_proto_ptc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_ptc_grpc_proto_ptc_proto_rawDesc), len(file_pkg_ptc_grpc_proto_ptc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_ptc_grpc_proto_ptc_proto_goTypes,
		DependencyIndexes: file_pkg_ptc_grpc_proto_ptc_proto_depIdxs,
		EnumInfos:         file_pkg_ptc_grpc_proto_ptc_proto_enumTypes,
		MessageInfos:      file_pkg_ptc_grpc_proto_ptc_proto_msgTypes,
	}.Build()
	File_pkg_ptc_grpc_proto_ptc_proto = out.File
	file_pkg_ptc_grpc_proto_ptc_proto_goTypes = nil
	file_pkg_ptc_grpc_proto_ptc_proto_depIdxs = nil
}
