// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: pkg/ptc/grpc/proto/ptc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PTCService_Execute_FullMethodName       = "/ptc.PTCService/Execute"
	PTCService_ExecuteStream_FullMethodName = "/ptc.PTCService/ExecuteStream"
	PTCService_ListTools_FullMethodName     = "/ptc.PTCService/ListTools"
	PTCService_GetToolInfo_FullMethodName   = "/ptc.PTCService/GetToolInfo"
)

// PTCServiceClient is the client API for PTCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PTCService provides programmatic tool calling functionality
type PTCServiceClient interface {
	// Execute runs code in a sandbox environment
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// ExecuteStream runs code and streams output
	ExecuteStream(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteChunk], error)
	// ListTools returns available tools
	ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error)
	// GetToolInfo returns information about a specific tool
	GetToolInfo(ctx context.Context, in *GetToolInfoRequest, opts ...grpc.CallOption) (*GetToolInfoResponse, error)
}

type pTCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPTCServiceClient(cc grpc.ClientConnInterface) PTCServiceClient {
	return &pTCServiceClient{cc}
}

func (c *pTCServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, PTCService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pTCServiceClient) ExecuteStream(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PTCService_ServiceDesc.Streams[0], PTCService_ExecuteStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteRequest, ExecuteChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PTCService_ExecuteStreamClient = grpc.ServerStreamingClient[ExecuteChunk]

func (c *pTCServiceClient) ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolsResponse)
	err := c.cc.Invoke(ctx, PTCService_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pTCServiceClient) GetToolInfo(ctx context.Context, in *GetToolInfoRequest, opts ...grpc.CallOption) (*GetToolInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToolInfoResponse)
	err := c.cc.Invoke(ctx, PTCService_GetToolInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PTCServiceServer is the server API for PTCService service.
// All implementations must embed UnimplementedPTCServiceServer
// for forward compatibility.
//
// PTCService provides programmatic tool calling functionality
type PTCServiceServer interface {
	// Execute runs code in a sandbox environment
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// ExecuteStream runs code and streams output
	ExecuteStream(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteChunk]) error
	// ListTools returns available tools
	ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error)
	// GetToolInfo returns information about a specific tool
	GetToolInfo(context.Context, *GetToolInfoRequest) (*GetToolInfoResponse, error)
	mustEmbedUnimplementedPTCServiceServer()
}

// UnimplementedPTCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPTCServiceServer struct{}

func (UnimplementedPTCServiceServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedPTCServiceServer) ExecuteStream(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteChunk]) error {
	return status.Error(codes.Unimplemented, "method ExecuteStream not implemented")
}
func (UnimplementedPTCServiceServer) ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedPTCServiceServer) GetToolInfo(context.Context, *GetToolInfoRequest) (*GetToolInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToolInfo not implemented")
}
func (UnimplementedPTCServiceServer) mustEmbedUnimplementedPTCServiceServer() {}
func (UnimplementedPTCServiceServer) testEmbeddedByValue()                    {}

// UnsafePTCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PTCServiceServer will
// result in compilation errors.
type UnsafePTCServiceServer interface {
	mustEmbedUnimplementedPTCServiceServer()
}

func RegisterPTCServiceServer(s grpc.ServiceRegistrar, srv PTCServiceServer) {
	// If the following call panics, it indicates UnimplementedPTCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PTCService_ServiceDesc, srv)
}

func _PTCService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PTCServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PTCService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PTCServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PTCService_ExecuteStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PTCServiceServer).ExecuteStream(m, &grpc.GenericServerStream[ExecuteRequest, ExecuteChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PTCService_ExecuteStreamServer = grpc.ServerStreamingServer[ExecuteChunk]

func _PTCService_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PTCServiceServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PTCService_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PTCServiceServer).ListTools(ctx, req.(*ListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PTCService_GetToolInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PTCServiceServer).GetToolInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PTCService_GetToolInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PTCServiceServer).GetToolInfo(ctx, req.(*GetToolInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PTCService_ServiceDesc is the grpc.ServiceDesc for PTCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PTCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ptc.PTCService",
	HandlerType: (*PTCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _PTCService_Execute_Handler,
		},
		{
			MethodName: "ListTools",
			Handler:    _PTCService_ListTools_Handler,
		},
		{
			MethodName: "GetToolInfo",
			Handler:    _PTCService_GetToolInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteStream",
			Handler:       _PTCService_ExecuteStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/ptc/grpc/proto/ptc.proto",
}
