# RAGO - Minimal Configuration (LM Studio)
# Get started with just 3 lines!

[providers]
default_llm = "ollama"

[providers.ollama]
type = "ollama"
base_url = "http://localhost:11434"
llm_model = "qwen3:8b"
embedding_model = "nomic-embed-text"
timeout = "120s"

[providers.lmstudio]
type = "lmstudio"
base_url = "http://localhost:1234"
llm_model = "qwen/qwen3-4b-2507"
embedding_model = "text-embedding-qwen3-embedding-4b"
timeout = "120s"

[mcp]
enabled = true                # Enable MCP servers
servers = ["./mcpServers.json"]  # MCP server configuration files
log_level = "info"           # Logging: "debug", "info", "warn", "error"
default_timeout = "60s"      # Request timeout
max_concurrent_requests = 10 # Parallel request limit
health_check_interval = "60s" # Server health monitoring

[agents]
enabled = true                      # Enable agent functionality
storage_type = "persistent"         # Use persistent database storage
data_path = ".rago/data"           # Path for database files (plans.db, rag.db)
workspace_path = ".rago/workspace" # Agent workspace for file operations
max_concurrent = 5                 # Maximum concurrent executions
default_timeout = 300              # Default timeout in seconds
enable_generation = true           # Enable workflow generation from natural language

[sqvect]
db_path = "./.rago/data/rag.db"