[tools]
enabled = true

[tools.builtin.datetime]
enabled = true

[tools.builtin.file_operations]
enabled = true

[tools.builtin.file_operations.parameters]
allowed_paths = ".,./knowledge,./data,./examples"
max_file_size = "10485760"